Add graphviz as submodule
KDAB/KDStateMachineEditor pull request #47
Opened 2024-01-14 15:20 UTC by dantti

2024-01-16 15:25 UTC, winterz requested changes

2024-01-16 15:25 UTC, winterz commented on src/core/CMakeLists.txt
>      if(WITH_INTERNAL_GRAPHVIZ)
we don't need this conditional block now

2024-01-16 15:25 UTC, winterz commented on .gitmodules
> +
remove all that header stuff and add .gitmodules into .reuse/dep5

2024-01-16 15:25 UTC, winterz commented on 3rdparty/CMakeLists.txt
> +# SPDX-FileCopyrightText: 2015-2023 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
change "2015-2023" to "2024"

2024-01-16 15:25 UTC, winterz commented on 3rdparty/CMakeLists.txt
> +    function(add_sonnet_subdirectory)
sonnet?

2024-01-16 16:36 UTC, dantti commented on 3rdparty/CMakeLists.txt
> +    function(add_sonnet_subdirectory)
weird that CI was happy

2024-06-21 19:43 UTC, winterz approved these changes

2024-06-21 19:43 UTC, merged